### PR TITLE
refactor: extract CVR file handling to its own class

### PR DESCRIPTION
**Pull request by eventualbuddha**
This extracts the CVR handling to its own class (with tests!). It _should_ address @benadida's comment about performance since I'm storing ballots in a `Map` from ballot ID to CVR.

### CODE REVIEW

**Comment by benadida** [comment]
Before we merge CVR de-duping, can we triple check the random number génération for the ballot ID? I'll see if I can find it....

**Comment by benadida** [comment]
> Before we merge CVR de-duping, can we triple check the random number génération for the ballot ID? I'll see if I can find it....

Ok the process looks good. I am a tad worried about *when* we generate the random ID, but I can live with it for now

**Comment by eventualbuddha** [comment]
> I am a tad worried about when we generate the random ID

Say more?

**Comment by benadida** [comment]
> > I am a tad worried about when we generate the random ID
> 
> Say more?

I'm a tad concerned that we generate the random ID right before we print the ballot. A better approach would be for the random ID to be essentially fixed the moment the ballot is first written to the card. That way, any duplication or double-print or other unusual event would result in a ballot with the same ID, which is what we want.

But, that's not a problem that needs to be addressed here. So all good.

**Pull request merged**
